// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu90IHm6beFU_J1NV35vzZeqjHjCZmBsA',
    appId: '1:195060731330:web:0b0c4d154f9afa1985da5b',
    messagingSenderId: '195060731330',
    projectId: 'campusplus-7c073',
    authDomain: 'campusplus-7c073.firebaseapp.com',
    storageBucket: 'campusplus-7c073.appspot.com',
    measurementId: 'G-YFSZVEHWS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVo6isLJ2uQLYP-r7I9HZqq1DrwotmTU',
    appId: '1:195060731330:android:dd72d1600ebd355585da5b',
    messagingSenderId: '195060731330',
    projectId: 'campusplus-7c073',
    storageBucket: 'campusplus-7c073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7yXZN4DEkuT3ndDM9psO9a1WdAxxgQjI',
    appId: '1:195060731330:ios:cd55d959a54f205e85da5b',
    messagingSenderId: '195060731330',
    projectId: 'campusplus-7c073',
    storageBucket: 'campusplus-7c073.appspot.com',
    iosClientId: '195060731330-ci3p7kj35iku3okhbkpa9k9h5va4m0kh.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusPlus',
  );
}
